[package]
name = "radio-at86rf212"
description = "Driver for the Atmel AT86RF212 Sub 1GHz ISM band radio IC"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { git="https://github.com/japaric/embedded-hal", features=["unproven"] }
nb = "0.1.1"

[dev-dependencies]
linux-embedded-hal = "0.2.0"
shared-bus = "0.1.2"

